### ISSUE TITLE
Add co-maintainer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ip_geoloc#12]
In a separate thread I invited @AlexHoebart-ICPDR to be a co-maintainer based on recent work on this module. [Follow-up question](https://github.com/backdrop-contrib/leaflet/issues/56#issuecomment-1987186465):

> What exactly does it mean to be a co-maintainer? Would you or someone else review my PRs?
Developing is just a part of my daily work and I mostly learned it by doing. And I don't use the full feature set of the ip_geoloc module. On the other hand, I used and customized Drupal since version 5 and still have several Drupal7 sites with considerable amount of custom modules and not-yet-ported modules to be migrated to Backdrop - so I already started to port some modules and consider contributing them as I see the benefits of that.

@AlexHoebart-ICPDR, to answer your question, I'd say:
1. You'd need to review and agree to the contrib guidelines and requirements as noted here, to be reviewed/accepted to the contrib team: https://github.com/backdrop-ops/contrib
2. You'd be listed as a co-maintainer on this module.
3. You'd be authorized in this module to make merges and releases as you felt comfortable, and since we have no official releases or fully functioning module here yet, the pressure is quite low.
4. You'd be able to request reviews from me or anyone else who is available (e.g. by posting to Zulip live chat)

I like adding co-maintainers so nobody feels like they are responsible for everything. Let me know if you feel comfortable and are interested.

**Comment by AlexHoebart-ICPDR** [comment]
I reviewed the guidelines and can agree with them. Should I fill in the application form?

I'm just not sure how to understand item 4 of the agreement: "You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later."
Does this prevent the Mini-Map library to be packaged with the ip_geoloc module?
It has a different license than GPL, but also allows redistribution:
https://github.com/Norkart/Leaflet-MiniMap/blob/master/LICENSE.txt

**Comment by laryn** [comment]
Any bundled code must be licensed with a compatible license. Based on this link it seems that BSD license should be compatible:

“ The BSD license is compatible with every major copyleft license, including GPL version 2.”

https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/

And yes, I’d say go ahead and sign the application form then! 👍
