### ISSUE TITLE
Library integration issue

### ISSUE THREAD

**Issue by hoorack** [backdrop-contrib/ip_geoloc#13]
Great work so far! I encountered two issues:

1.  the module fails to install as it calls the function leaflet_markercluster_get_library_path, which the backdrop version of leaflet_markercluster (sub)module does not contain due to embedded markercluster library. I think the path could therefore be fixed, if the leaflet.markercluster module is found.

2. When chosen as a view format "Map (Leaflet API, via IPGV&M)", the leaflet library is not loaded (so you get the "L is not defined" JS error).

**Comment by AlexHoebart-ICPDR** [comment]
This should be fixed by https://github.com/backdrop-contrib/ip_geoloc/pull/9

**Comment by laryn** [comment]
@AlexHoebart-ICPDR I merged with a visual review, which I think is sufficient given it's fixing things that don't work currently, and we don't have a formal release yet. I would like to also [renew my invitation here](https://github.com/backdrop-contrib/ip_geoloc/issues/12) to join as a co-maintainer -- if you'd like to, submit a PR with your name added to the README and I'll merge and give you access.
