### ISSUE TITLE
Drupal reference in plugin style map

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/ip_geoloc#3]
`Warning: Use of undefined constant BACKDROP_ANONYMOUS_RID - assumed 'BACKDROP_ANONYMOUS_RID' (this will throw an Error in a future version of PHP) in ip_geoloc_plugin_style_map->option_definition() (line 36 of /app/modules/contrib/ip_geoloc/views/ip_geoloc_plugin_style_map.inc).`
`Warning: Use of undefined constant BACKDROP_AUTHENTICATED_RID - assumed 'BACKDROP_AUTHENTICATED_RID' (this will throw an Error in a future version of PHP) in ip_geoloc_plugin_style_map->option_definition() (line 37 of /app/modules/contrib/ip_geoloc/views/ip_geoloc_plugin_style_map.inc).`

Warning displays on views displays that are set to "map (Leaflet API, via IPGV&M)" format. Cannot open the format settings in the view with this format enabled. The map will not display in the view.

Getting this error on a Backdrop site converted from a D7 site running on PHP 7.4.

**Comment by laryn** [comment]
@pgrayove-mcpl Would you like to submit a PR that changes both `*_RID` constants to `*_ROLE`? Those constant names changed from Drupal to Backdrop with the move to configuration management, since the role ID was removed in favor of the role name.

**Comment by pgrayove-mcpl** [comment]
Sure.
