### ISSUE TITLE
View format settings error

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/ip_geoloc#5]
Cannot edit settings for ip_geoloc "Map (Leaflet API, via IPGV&M)" format. Displays this error:

`Error: Call to undefined function leaflet_markercluster_get_library_path() in ip_geoloc_plugin_style_leaflet->options_form() (line 199 of /app/modules/contrib/ip_geoloc/views/ip_geoloc_plugin_style_leaflet.inc).`

The view also displays this error:

`Warning: in_array() expects parameter 2 to be array, null given in ip_geoloc_generator_ip_geoloc_marker_locations_alter() (line 38 of /app/modules/contrib/ip_geoloc/ip_geoloc_generator/ip_geoloc_generator.module).`

**Comment by pgrayove-mcpl** [comment]
Probably should have listed this error as a separate issue.  This error goes away when settings in /admin/config/system/ip_geoloc_generator are not empty/null.  Maybe there should be defaults for those settings or a link in the error to the settings.  
`Warning: in_array() expects parameter 2 to be array, null given in ip_geoloc_generator_ip_geoloc_marker_locations_alter() (line 38 of /app/modules/contrib/ip_geoloc/ip_geoloc_generator/ip_geoloc_generator.module).
`

**Comment by pgrayove-mcpl** [comment]
There's some problem between ip_geoloc and leaflet modules causing this error.  If I turn off the leaflet markercluster submodule, I can edit the Map (Leaflet API, via IPGV&M) format settings, but then I get this error:
`Notice: Undefined index: allow_clusters_of_one in ip_geoloc_plugin_style_leaflet->_add_markercluster() (line 703 of /app/modules/contrib/ip_geoloc/views/ip_geoloc_plugin_style_leaflet.inc).`

**Comment by pgrayove-mcpl** [comment]
I should have mentioned that these are the lines referenced in the ip_geoloc_plugin_style_leaflet.inc
Line 199: `$lib_markercluster = module_exists('leaflet_markercluster') ? leaflet_markercluster_get_library_path() : FALSE;`
Line 703: `'#default_value' => $this->options['allow_clusters_of_one'],`

**Comment by AlexHoebart-ICPDR** [comment]
This issue should be fixed by this PR https://github.com/backdrop-contrib/ip_geoloc/pull/9

**Comment by laryn** [comment]
That PR has been merged. @pgrayove-mcpl if you are interested in testing, please respond here to verify whether or not this is now solved in the latest code.

**Comment by pgrayove-mcpl** [comment]
I've tested briefly and it works so far without any errors or issues.  There are a lot of map settings in views and custom markers on my site to fully test, but with defaults in place I don't see any problems for the "Map (Leaflet API, via IPGV&M)" format in views. I also have Leaflet markercluster submodule enabled without issues.

**Comment by laryn** [comment]
Thank you! I'll close this for now, then. If you run into any other issues feel free to reopen or start a new one.
