### ISSUE TITLE
PHP 7.4 parenthesis missing notice

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/ip_geoloc#6]
`Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /app/modules/contrib/ip_geoloc/views/ip_geoloc_plugin_style.inc on line 469`

Looks like it can be updated from [this Drupal patch](https://www.drupal.org/project/ip_geoloc/issues/3177202)

In `/views/ip_geoloc_plugin_style.inc`

Change line 469: `$items[0] = empty($differentiator_value) ? array() : is_array($differentiator_value) ? $differentiator_value : array($differentiator_value);`

to: `$items[0] = empty($differentiator_value) ? array() : (is_array($differentiator_value) ? $differentiator_value : array($differentiator_value));`

**Comment by laryn** [comment]
Looks great @pgrayove-mcpl -- can you submit as a PR?

**Comment by laryn** [comment]
Oh, I just saw https://github.com/backdrop-contrib/ip_geoloc/pull/7

Note that if you put "Fixes #x" at the top of the first comment in a PR it will link it to the issue automatically.
